### ISSUE TITLE
Consider Traefik or similar for HTTPS etc. (milestone E)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10359]
As discussed in Mexico.

The use case is having Dataverse on a server that you want to show to a non-technical audience. That audience shouldn't have to worry about SSL certs or being on weird ports like 8080.

It doesn't have to be Traefik. It could be nginx or similar.

Do we want to use certbot from Let's Encrypt by default? Or let people bring their own cert.

**Comment by pdurbin** [comment]
Over at https://github.com/rspace-os/rspace-dataverse-adapter/issues/2#issuecomment-3296446233 @akos326 is using nginx, saying, "I needed https support, otherwise my RSpace instance wasn't able to parse the response from the local Dataverse, that's why I added the nginx entry to the end of compose.yml":

```
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - dataverse
    depends_on:
      - dataverse
```
