### ISSUE TITLE
Feature Request: Click on the URL hidden behind a rolled-up description overlay

### ISSUE THREAD

**Issue by super-lou** [IQSS/dataverse#11058]
**Overview of the Feature Request**
Add the possibility to click on a tag url in description field of dataverse or dataset even if the description is rolled up.

**What kind of user is the feature intended for?**
All

**What inspired the request?**
On this [dataverse](https://entrepot.recherche.data.gouv.fr/dataverse/explore2) the description field is long with <a> tag on the first line that is important for rapid access to some dataset or resources but it feels conter intuitive to not be able to click on it directly and that we have to unroll the description first.

**What existing behavior do you want changed?**
Remove the blocking of pointer event of the overlay in rolled up description field.

**Are you thinking about creating a pull request for this feature?**  
I would like to open a PR but it look like i dont have the permission to.
Solution :
``` css
button.desc-more-link {
  padding: 0;
  pointer-events: auto;
  margin-top: 30px;
  margin-left: auto;
  margin-right: auto;
  display: flex;
  justify-content: center;
}

div.more-block {
  ...
  pointer-events: none;
}

```
