### ISSUE TITLE
Feature Request/Idea: Make URLs in the Description field "preview" clickable

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#8340]
**Overview of the Feature Request**
The aim of this feature request is to make URLs in the Description field "preview" on the dataset landing page clickable.

**What kind of user is the feature intended for?**
The feature is intended for end users to make it easier to access URLs included in the Description field of the Citation Metadata Schema.

**What inspired the request?**
The feature was requested by a depositor who added an important URL on top of the Description field on the dataset landing page.

**What existing behavior do you want changed?**
Currently (v. 5.9), URLs in the Description field on the file landing page are only clickable after expanding the field by clicking the Read Full Description [+] button.

**Comment by super-lou** [comment]
i found a solution for that and I would like to open a PR but it look like i dont have the permission to.

``` css
button.desc-more-link {
  padding: 0;
  pointer-events: auto;
  margin-top: 30px;
  margin-left: auto;
  margin-right: auto;
  display: flex;
  justify-content: center;
}

div.more-block {
  ...
  pointer-events: none;
}

```

**Comment by super-lou** [comment]
description example where this feature can be useful : [link](https://entrepot.recherche.data.gouv.fr/dataverse/explore2)

**Comment by qqmyers** [comment]
The changes to pointer-events looks reasonable to me (not sure why the other style changes are needed.) In any case, you should be able to [make a pull request.](https://guides.dataverse.org/en/latest/developers/version-control.html#how-to-make-a-pull-request) The one thing that may not be apparent is that you'll need to create your own repository by cloning/forking the Dataverse repo.

**Comment by pdurbin** [comment]
We do say "Push your feature branch to your fork of the Dataverse Software." However, if there's anything confusing in that doc, we're happy to fix it!

**Comment by super-lou** [comment]
Firstly, thank you so much, @pdurbin, for your advice! I should have taken the time to read the documentation more thoroughly.

Regarding my suggested solution, I attempted to add this feature using the code above, but I encountered some issues. Specifically, the challenge lies in maintaining the ability to click on the "More Description" button without being obstructed by a URL positioned directly behind it.

To address this, I included the following CSS to create a reserved, unclickable area for the "More Description" button:

``` css
button.desc-more-link {
  padding: 0;
  pointer-events: auto;
  margin-top: 30px;
  margin-left: auto;
  margin-right: auto;
  display: flex;
  justify-content: center;
}
```  

However, I couldn't get it to work as intended purely with CSS because of the HTML priority structure.

Unfortunately, I don’t have the time right now to dive deeper into this issue or set up a local Dataverse instance to test more advanced solutions. So, I’m leaving this open for anyone else who might want to take a shot at it !
