### ISSUE TITLE
Improve spin up script to also deploy new dataverse-frontend repo

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9347]
We just created a new repo for frontend code at https://github.com/IQSS/dataverse-frontend

Obviously, our spin up script (ec2-create-instance.sh), doesn't yet know about this new repo.

Let's add a new flag (`-f` for frontend?) to what's currently documented at https://guides.dataverse.org/en/5.12.1/developers/deployment.html

![Screen Shot 2023-01-30 at 11 45 41 AM](https://user-images.githubusercontent.com/21006/215541127-10379ec1-be00-4858-999f-77bdcd74c282.png)

The code to change in this repo is just the docs above.

The script itself lives in this repo: https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible and here's the issue for working on the script itself:

- https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/issues/266

**Comment by pdurbin** [comment]
Related:

- https://github.com/IQSS/dataverse-frontend/issues/6

**Comment by pdurbin** [comment]
Done! By @donsizemore in this PR:

- https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/pull/278

To enable the new frontend, you flip this to enabled in a local copy of main.yml and pass `-g main.yml`:

```
  frontend:
    branch: develop
    enabled: false
    docroot:
      base: /var/www/html
      dir: spa
    nodejs:
      version: 18
    repo: "http://github.com/IQSS/dataverse-frontend"
    srcdir: /tmp/dataverse-frontend
```

Thanks, @donsizemore!  🎉
