### ISSUE TITLE
UTF8 coding problems OAI-PMH?

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#9987]
**What steps does it take to reproduce the issue?**

The OAI request
https://heidata.uni-heidelberg.de/oai?verb=ListRecords&resumptionToken=b2Zmc2V0OjozMHxwcmVmaXg6Om9haV9kZGk=
results in a non-valid XML. Apparently the apostrophe in the author name for https://heidata.uni-heidelberg.de/dataset.xhtml?persistentId=doi:10.11588/data/10034 (Siang, Ch’ng Kean) is not encoded correctly.

Firefox reports that the xml is not well-formed. And also jhove reports an error:

If I export the metadata directly to an XML format (for example https://heidata.uni-heidelberg.de/api/datasets/export?exporter=Datacite&persistentId=doi%3A10.11588/data/10034), the encoding is apparently correct.
```

jhove -m XML-hul oai.xml
Jhove (Rel. 1.20.0, 2019-01-19)
 Date: 2023-10-10 08:30:46 CEST
 RepresentationInformation: oai.xml
  ReportingModule: XML-hul, Rel. 1.4 (2007-01-08)
  LastModified: 2023-10-10 08:29:58 CEST
  Size: 75357
  Format: XML
  Status: Not well-formed
  SignatureMatches:
   XML-hul
  ErrorMessage: Invalid byte 1 of 1-byte UTF-8 sequence.: Line = 3, Column = 17702
  MIMEtype: text/xml
```

* When does this issue occur?

OAI-PMH requests. Maybe all UTF-8-Codepoints with more then two bytes?

* Which page(s) does it occurs on?

https://heidata.uni-heidelberg.de/oai?verb=ListRecords&resumptionToken=b2Zmc2V0OjozMHxwcmVmaXg6Om9haV9kZGk=

* What happens?

see above

* To whom does it occur (all users, curators, superusers)?

All OAI-PMH users

* What did you expect to happen?

Same coding as for frontend and other exports.

**Which version of Dataverse are you using?**

5.13
